version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    # bind mount a host folder so data persists even if you remove the container/image
    volumes:
      - ./node-red-data:/data
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - "1883:1883"   
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt &&
              rabbitmq-server"
    networks:
      - node-red-net
    # bind mount host folders to persist RabbitMQ data and logs
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
  iot-simulator:
    build: ./IoTSimulator
    ports:
      - "9000:9000"
      - "12345:12345"
    volumes:
      - ./IoTSimulator/data:/app/data
      - ./IoTSimulator/log:/app/log
    networks:
      - node-red-net
  influxdb:
    image: influxdb:2  # Using a common stable version for IoT/Node-RED setups
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086" # InfluxDB HTTP API port
    volumes:
      # Mount host folder for persistent storage of the database data
      - ./influxdb-data:/var/lib/influxdb
    environment:
      # These environment variables are used for initial database setup (optional for 1.x)
      - INFLUXDB_DB=iot_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_USER=node-red-user
      - INFLUXDB_USER_PASSWORD=noderedpassword
    networks:
      - node-red-net
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  

networks:
  node-red-net:
